version: '3.9'
services:
  broker:
    image: openjdk:21-bookworm
    volumes:
      - ./dist/:/broker/dist/
    ports:
      - '7000:7000'
      - '8000:8080'
    environment:
      JAVA_TOOL_OPTIONS:
    entrypoint: /bin/sh -c 'java -jar /broker/dist/jr-broker-*.jar'
