version: '3.9'
services:
  petclinic-dev:
    depends_on:
      - supplements-api
    image: docker.io/library/spring-petclinic:3.4.0-SNAPSHOT
    volumes:
      - ./dist/jrebel:/jrebel # JREBEL agent
    ports:
      - '8081:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENV=dev
      - |
        JAVA_TOOL_OPTIONS=
        -XX:MaxMetaspaceSize=256M
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -agentpath:/jrebel/lib/libjrebel64.so 
        -Drebel.broker.url=http://host.docker.internal:7000/zone/frontend-dev
        -Drebel.broker.jvm_name=petclinic-dev

  petclinic-staging:
    depends_on:
      - supplements-api
    image: docker.io/library/spring-petclinic:3.4.0-SNAPSHOT
    volumes:
      - ./dist/jrebel:/jrebel # JREBEL agent
    ports:
      - '8082:8080'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENV=staging
      - |
        JAVA_TOOL_OPTIONS=
        -XX:MaxMetaspaceSize=256M
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -agentpath:/jrebel/lib/libjrebel64.so 
        -Drebel.broker.url=http://host.docker.internal:7000/zone/frontend-staging
        -Drebel.broker.jvm_name=petclinic-staging

  supplements-api:
    #image: tomcat:9.0-jdk21
    build:
        context: demo-app/supplements-api
    volumes:
      - ./dist/jrebel:/jrebel # JREBEL agent
      #- ./demo-app/supplements-api/target/api-server-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/supplements-api.war
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -XX:MaxMetaspaceSize=256M
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -agentpath:/jrebel/lib/libjrebel64.so 
        -Drebel.broker.url=http://host.docker.internal:7000/zone/backend
        -Drebel.broker.jvm_name=supplements-api      
